### ISSUE TITLE
顶部尺子没有根据滚动条滚动

### ISSUE THREAD

**Issue by armomu** [armomu/oreo-editor#6]

**Comment by kakajun** [comment]
尺规推荐用2x    [vue3-sketch-ruler](https://github.com/kakajun/vue3-sketch-ruler)

**Comment by armomu** [comment]
> 尺规推荐用2x [vue3-sketch-ruler](https://github.com/kakajun/vue3-sketch-ruler)

这个牛逼，不过看着好像不好放进来，我这里就缺个缩放，刚好可以参考下
